language: c++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - g++-6
            - gcc-6
            - cmake
            - cmake-data
            - libx11-xcb-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxcb-image0-dev
            - libxcb-randr0-dev
            - libudev-dev
            - libopenal-dev
            - freeglut3-dev
            - libjpeg-dev
            - libfreetype6-dev
            - libxrandr-dev
            - libglew-dev
            - libsndfile1-dev
            - libasound2-dev 
            - alsa-utils 
            - alsa-oss

env:
  - PLATFORM=linux
  #- PLATFORM=android

git:
  submodules: false

script:
  - ./.travis_build.sh
